export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_PRIVATE_POSTS = "GET_PRIVATE_POSTS";
export const GET_PUBLIC_POSTS = "GET_PUBLIC_POSTS";
export const SET_LOADING = "SET_LOADING";
